<?php
/**
 * ══════════════════════════════════════════════════════════════════════════
 *  ⚠️ 开发测试专用 —— 清空站点内容数据（WIPE）
 *  ⚠️ 此文件禁止随安装包 / 发布包分发！发布前必须删除本文件及全部 cli_*.php
 * ══════════════════════════════════════════════════════════════════════════
 *
 * 一键清空「内容」数据，用于反复测试数据导入等功能，让每次测试从干净状态开始。
 *
 * 用法（需 MySQL 可用，在站点根目录执行）：
 *   php usr/plugins/data-import/cli_wipe_content.php              # 交互确认后清空全部内容
 *   php usr/plugins/data-import/cli_wipe_content.php --yes        # 跳过确认直接清空
 *   php usr/plugins/data-import/cli_wipe_content.php --dry-run    # 只显示各表行数，不清空
 *   php usr/plugins/data-import/cli_wipe_content.php --keep-attachments  # 保留附件记录
 *   php usr/plugins/data-import/cli_wipe_content.php --keep-tags-cats    # 保留分类/标签
 *   php usr/plugins/data-import/cli_wipe_content.php --keep-all   # 只清文章/页面/评论
 *   php usr/plugins/data-import/cli_wipe_content.php --backup-dir=C:/path/to/dir  # 自定义备份目录（默认 C:/xampp/verda_backup，不可写时回退站点内 usr/uploads/backup）
 *
 * 安全机制：
 *   1. 清空前自动备份全部内容表到 C:\xampp\verda_backup\verda_content_wipe_*.sql（备份失败即中止）
 *   2. 白名单硬编码：只清下列 6 张内容表，绝不触碰 vd_users / vd_options / vd_menus
 *      / 登录限制 / 收藏 / 浏览轨迹 / 批注 / 纠错 / 插件表（nav_links、slc_* 等）
 *   3. 默认交互确认，需输入 yes；仅 --yes 可跳过
 *   4. 只清数据库记录，不删除 usr/uploads 下任何物理文件
 */

$root = dirname(__DIR__, 3);
if (!defined('RYEBLOG_ROOT')) {
    define('RYEBLOG_ROOT', $root);
}

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "仅限命令行运行：php usr/plugins/data-import/cli_wipe_content.php\n");
    exit(1);
}

require_once $root . '/inc/functions.php';

if (!db()) {
    fwrite(STDERR, "数据库不可用（install.php 未完成？）。\n");
    exit(1);
}

/* ---------- 参数解析 ---------- */
$args = array_slice($argv, 1);
$flags = [
    'yes'             => in_array('--yes', $args, true),
    'dry_run'         => in_array('--dry-run', $args, true),
    'keep_attachments'=> in_array('--keep-attachments', $args, true),
    'keep_tags_cats'  => in_array('--keep-tags-cats', $args, true),
    'keep_all'        => in_array('--keep-all', $args, true),
];
// 备份目录：--backup-dir=路径 或默认 C:/xampp/verda_backup；不可写时回退站点内 usr/uploads/backup
$backupDir = 'C:/xampp/verda_backup';
foreach ($args as $a) {
    if (strpos($a, '--backup-dir=') === 0) {
        $backupDir = substr($a, strlen('--backup-dir='));
    }
}

/* ---------- 内容表白名单（只清这些） ---------- */
$contentTables = [
    'vd_posts'       => '文章 / 页面 / 草稿',
    'vd_post_tags'   => '文章-标签关联',
    'vd_comments'    => '评论',
    'vd_attachments' => '附件记录（物理文件保留）',
    'vd_categories'  => '分类',
    'vd_tags'        => '标签',
];
if ($flags['keep_attachments']) unset($contentTables['vd_attachments']);
if ($flags['keep_tags_cats'])   { unset($contentTables['vd_categories']); unset($contentTables['vd_tags']); }
if ($flags['keep_all'])         { unset($contentTables['vd_categories'], $contentTables['vd_tags'], $contentTables['vd_attachments']); }

/* 绝不触碰的保留表（展示用，不参与任何 SQL） */
$keepTables = ['vd_users', 'vd_options', 'vd_menus', 'vd_login_attempts', 'vd_trail',
               'vd_favorites', 'vd_annotations', 'vd_corrections'];

echo "══════════════════════════════════════════════════════════\n";
echo "  ⚠️  内容数据清空工具（开发测试专用）\n";
echo "══════════════════════════════════════════════════════════\n\n";

if ($flags['dry_run']) {
    echo "【DRY-RUN】仅预览，不执行任何删除。\n\n";
}
echo "将清空的表（白名单）：\n";
$totalRows = 0;
foreach ($contentTables as $t => $label) {
    $n = (int)(dbOne("SELECT COUNT(*) c FROM $t")['c'] ?? 0);
    $totalRows += $n;
    printf("  - %-16s %s  (%d 行)\n", $t, $label, $n);
}
echo "\n将保留的表：\n  " . implode(' / ', $keepTables) . "\n";
if ($flags['keep_attachments']) echo "  （另保留附件记录 vd_attachments）\n";
if ($flags['keep_tags_cats'])   echo "  （另保留分类/标签）\n";
if ($totalRows === 0) {
    echo "\n内容表已全部为空，无需清空。\n";
    exit(0);
}
echo "\n共 " . $totalRows . " 行将被清空。\n";

if ($flags['dry_run']) {
    echo "\n（DRY-RUN 结束，未做任何改动）\n";
    exit(0);
}

/* ---------- 自动备份（失败即中止） ---------- */
if (!is_dir($backupDir)) {
    @mkdir($backupDir, 0777, true);
}
if (!is_writable($backupDir)) {
    // 回退到站点内目录，避免硬编码路径在其它环境失效
    $backupDir = RYEBLOG_ROOT . '/usr/uploads/backup';
    if (!is_dir($backupDir)) @mkdir($backupDir, 0777, true);
    if (!is_writable($backupDir)) {
        fwrite(STDERR, "备份目录不可写，已中止（未清空任何数据）。\n");
        exit(1);
    }
}
$stamp = date('Ymd_His');
$backupFile = $backupDir . '/verda_content_wipe_' . $stamp . '.sql';
echo "\n正在备份到 " . $backupFile . " ...\n";

$lines = ["-- RyeBlog content wipe backup " . date('Y-m-d H:i:s'), "-- Generated by cli_wipe_content.php — restore with: mysql -u root verda < " . basename($backupFile), "SET NAMES utf8mb4;", ""];
foreach ($contentTables as $t => $label) {
    $rows = dbAll("SELECT * FROM $t");
    if (!$rows) continue;
    $lines[] = "-- $t ({$label}): " . count($rows) . " rows";
    foreach ($rows as $r) {
        $cols = array_keys($r);
        $vals = [];
        foreach ($cols as $c) {
            $v = $r[$c];
            $vals[] = ($v === null) ? 'NULL' : db()->quote((string)$v);
        }
        $lines[] = "INSERT INTO `$t` (`" . implode('`,`', $cols) . "`) VALUES (" . implode(',', $vals) . ");";
    }
    $lines[] = "";
}
$backupSql = implode("\n", $lines);
if (file_put_contents($backupFile, $backupSql) === false) {
    fwrite(STDERR, "备份写入失败，已中止（未清空任何数据）。\n");
    exit(1);
}
echo "备份完成：" . filesize($backupFile) . " 字节。\n";

/* ---------- 确认 ---------- */
if (!$flags['yes']) {
    echo "\n确认清空以上 " . $totalRows . " 行内容数据？此操作不可撤销（备份已生成，可用上方 SQL 恢复）。\n";
    echo "输入 yes 继续：";
    $line = trim(fgets(STDIN));
    if ($line !== 'yes') {
        echo "已取消，未做任何改动。\n";
        exit(0);
    }
}

/* ---------- 清空（按外键依赖逆序：先子表后父表） ---------- */
echo "\n清空中...\n";
$wipeOrder = ['vd_post_tags', 'vd_comments', 'vd_attachments', 'vd_posts', 'vd_tags', 'vd_categories'];
foreach ($wipeOrder as $t) {
    if (!isset($contentTables[$t])) continue;
    dbQuery("DELETE FROM $t");
    // 自增归零，保证导入测试从 id=1 开始
    $pdo = db();
    try { $pdo->exec("ALTER TABLE $t AUTO_INCREMENT = 1"); } catch (Throwable $e) {}
    printf("  ✓ %-16s 已清空\n", $t);
}

echo "\n══════════════════════════════════════════════════════════\n";
echo "  完成。内容数据已清空，可开始新的导入测试。\n";
echo "  恢复备份：mysql -u root verda < " . $backupFile . "\n";
echo "  ⚠️  usr/uploads 下的物理文件未删除（附件记录已清）。\n";
echo "══════════════════════════════════════════════════════════\n";
exit(0);
